name: 'build'

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_jar:
    name: 'build on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout # it's duplicate, but it's too annoying to split build steps just to avoid it
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: apt update (on Linux)
      if: matrix.os == 'ubuntu-20.04'
      run: |
        sudo apt-get update
        echo y | sudo apt-get install doxygen cmake ninja-build libasound2-dev libjack-jackd2-dev
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: setup gpg necessities
      run: sudo bash -c "echo '$GPG_KEY_CONTENTS' | base64 -d > '$SIGNING_SECRET_KEY_RING_FILE'"
      env:
        GPG_KEY_CONTENTS: ${{ secrets.GPG_KEY_CONTENTS }}
        SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
    - name: rewrite build.gradle to require signing
      run: sed -i "s/signing {}/signing { sign(publishing.publications) }/" rtmidi-javacpp/build.gradle
    - name: build jar
      run:
         ./gradlew --warning-mode all publish
      env:
        OSSRH_USERNAME: atsushieno
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
    - name: upload artifact - Jar
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: rtmidi-javacpp-jars
        path: rtmidi-javacpp/build/libs/*.jar
