name: 'build'

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_jar:
    name: 'build on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-12, windows-latest]
    steps:
    - name: checkout # it's duplicate, but it's too annoying to split build steps just to avoid it
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: apt update (on Linux)
      if: matrix.os == 'ubuntu-20.04'
      run: |
        sudo apt-get update
        echo y | sudo apt-get install doxygen cmake ninja-build libasound2-dev libjack-jackd2-dev
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: build jar
      run:
         ./gradlew --warning-mode all build
    - name: upload artifact - Jar
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: rtmidi-javacpp-jars
        path: rtmidi-javacpp/build/libs/*.jar
